// Usage: go run ./cmd/server/main.go
package main

import (
	"context"
	"fmt"
	"log"
	"net/http"

	"github.com/bufbuild/connect-go"
	"github.com/rs/cors"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	greetv1 "hello-go/gen/greet/v1"        // generated by protoc-gen-go
	"hello-go/gen/greet/v1/greetv1connect" // generated by protoc-gen-connect-go
)

// GreetServer implements greetv1.GreetServiceServer.
type GreetServer struct{}

// Greet implements greetv1.GreetServiceServer.
func (s *GreetServer) Greet(
	ctx context.Context,
	req *connect.Request[greetv1.GreetRequest],
) (*connect.Response[greetv1.GreetResponse], error) {
	log.Println("Request headers: ", req.Header())
	res := connect.NewResponse(&greetv1.GreetResponse{
		Greeting: fmt.Sprintf("Hello, %s!", req.Msg.Name),
	})
	res.Header().Set("Greet-Version", "v1")
	return res, nil
}

func main() {
	greeter := &GreetServer{}
	mux := http.NewServeMux()
	path, handler := greetv1connect.NewGreetServiceHandler(greeter)
	mux.Handle(path, handler)

	log.Println("Ready - Server is running at localhost:8080")
	http.ListenAndServe(
		"0.0.0.0:8080",
		// Use h2c so we can serve HTTP/2 without TLS.
		// cors.Default() setup the middleware with default options being
		cors.Default().Handler(h2c.NewHandler(mux, &http2.Server{})),
	)
}
