// @generated by protoc-gen-connect-web v0.8.6 with parameter "target=ts"
// @generated from file greet/v1/greet.proto (package greet.v1, syntax proto3)

/* eslint-disable */
// @ts-nocheck
import { MethodKind } from "@bufbuild/protobuf";

import { GreetRequest, GreetResponse } from "./greet_pb.js";

/**
 * @generated from service greet.v1.GreetService
 */
export const GreetService = {
  typeName: "greet.v1.GreetService",
  methods: {
    /**
     * @generated from rpc greet.v1.GreetService.Greet
     */
    greet: {
      name: "Greet",
      I: GreetRequest,
      O: GreetResponse,
      kind: MethodKind.Unary,
    },
  },
} as const;
