// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file protos/hello.proto (package helloworld, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * The request message containing the user's name.
 *
 * @generated from message helloworld.HelloRequest
 */
export class HelloRequest extends Message<HelloRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  constructor(data?: PartialMessage<HelloRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helloworld.HelloRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): HelloRequest {
    return new HelloRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): HelloRequest {
    return new HelloRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): HelloRequest {
    return new HelloRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a: HelloRequest | PlainMessage<HelloRequest> | undefined,
    b: HelloRequest | PlainMessage<HelloRequest> | undefined,
  ): boolean {
    return proto3.util.equals(HelloRequest, a, b);
  }
}

/**
 * The response message containing the greetings
 *
 * @generated from message helloworld.HelloReply
 */
export class HelloReply extends Message<HelloReply> {
  /**
   * @generated from field: string message = 1;
   */
  message = "";

  constructor(data?: PartialMessage<HelloReply>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helloworld.HelloReply";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): HelloReply {
    return new HelloReply().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): HelloReply {
    return new HelloReply().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): HelloReply {
    return new HelloReply().fromJsonString(jsonString, options);
  }

  static equals(
    a: HelloReply | PlainMessage<HelloReply> | undefined,
    b: HelloReply | PlainMessage<HelloReply> | undefined,
  ): boolean {
    return proto3.util.equals(HelloReply, a, b);
  }
}
